
  create table "public"."business_social_links" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "active" boolean not null default true,
    "business_id" uuid not null default gen_random_uuid(),
    "platform" character varying not null,
    "url" character varying not null,
    "sort_order" bigint not null default '0'::bigint
      );


alter table "public"."business_social_links" enable row level security;


  create table "public"."businesses" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "udpated_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "slug" character varying not null,
    "description" text,
    "phone" character varying,
    "whatsapp_phone" character varying,
    "email" character varying,
    "address" character varying,
    "city" character varying,
    "country" character varying,
    "website_url" character varying,
    "active" boolean not null default true,
    "user_id" uuid not null default gen_random_uuid()
      );


alter table "public"."businesses" enable row level security;


  create table "public"."catalog_sections" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "title" character varying not null,
    "description" text,
    "sort_order" bigint not null default '0'::bigint,
    "active" boolean not null default true,
    "catalog_id" uuid not null default gen_random_uuid()
      );


alter table "public"."catalog_sections" enable row level security;


  create table "public"."catalog_slides" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "active" boolean,
    "title" character varying,
    "description" text,
    "link_url" character varying,
    "sort_order" bigint not null,
    "catalog_id" uuid not null default gen_random_uuid()
      );


alter table "public"."catalog_slides" enable row level security;


  create table "public"."catalogs" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "active" boolean not null default true,
    "name" character varying not null,
    "slug" character varying not null,
    "description" text,
    "business_id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null default gen_random_uuid()
      );


alter table "public"."catalogs" enable row level security;


  create table "public"."product_prices" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "active" boolean not null default true,
    "label" character varying not null,
    "price" numeric not null,
    "sort_order" integer not null default 0,
    "product_id" uuid default gen_random_uuid()
      );


alter table "public"."product_prices" enable row level security;


  create table "public"."products" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying not null,
    "slug" character varying not null,
    "description" text,
    "base_price" numeric,
    "currency" character varying default 'BOB'::character varying,
    "is_on_sale" boolean default true,
    "sale_label" character varying,
    "sort_order" bigint default '0'::bigint,
    "active" boolean default true
      );


alter table "public"."products" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text not null,
    "full_name" text,
    "avatar_url" text,
    "username" text,
    "bio" text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX business_social_links_pkey ON public.business_social_links USING btree (id);

CREATE UNIQUE INDEX businesses_pkey ON public.businesses USING btree (id);

CREATE UNIQUE INDEX businesses_slug_key ON public.businesses USING btree (slug);

CREATE UNIQUE INDEX catalog_sections_pkey ON public.catalog_sections USING btree (id);

CREATE UNIQUE INDEX catalog_slides_pkey ON public.catalog_slides USING btree (id);

CREATE UNIQUE INDEX catalogs_pkey ON public.catalogs USING btree (id);

CREATE UNIQUE INDEX catalogs_slug_key ON public.catalogs USING btree (slug);

CREATE UNIQUE INDEX product_prices_pkey ON public.product_prices USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE INDEX profiles_username_idx ON public.profiles USING btree (username);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

alter table "public"."business_social_links" add constraint "business_social_links_pkey" PRIMARY KEY using index "business_social_links_pkey";

alter table "public"."businesses" add constraint "businesses_pkey" PRIMARY KEY using index "businesses_pkey";

alter table "public"."catalog_sections" add constraint "catalog_sections_pkey" PRIMARY KEY using index "catalog_sections_pkey";

alter table "public"."catalog_slides" add constraint "catalog_slides_pkey" PRIMARY KEY using index "catalog_slides_pkey";

alter table "public"."catalogs" add constraint "catalogs_pkey" PRIMARY KEY using index "catalogs_pkey";

alter table "public"."product_prices" add constraint "product_prices_pkey" PRIMARY KEY using index "product_prices_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."business_social_links" add constraint "business_social_links_business_id_fkey" FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE not valid;

alter table "public"."business_social_links" validate constraint "business_social_links_business_id_fkey";

alter table "public"."businesses" add constraint "businesses_slug_key" UNIQUE using index "businesses_slug_key";

alter table "public"."businesses" add constraint "businesses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."businesses" validate constraint "businesses_user_id_fkey";

alter table "public"."catalog_sections" add constraint "catalog_sections_catalog_id_fkey" FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id) ON DELETE CASCADE not valid;

alter table "public"."catalog_sections" validate constraint "catalog_sections_catalog_id_fkey";

alter table "public"."catalog_slides" add constraint "catalog_slides_catalog_id_fkey" FOREIGN KEY (catalog_id) REFERENCES public.catalogs(id) ON DELETE CASCADE not valid;

alter table "public"."catalog_slides" validate constraint "catalog_slides_catalog_id_fkey";

alter table "public"."catalogs" add constraint "catalogs_business_id_fkey" FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE not valid;

alter table "public"."catalogs" validate constraint "catalogs_business_id_fkey";

alter table "public"."catalogs" add constraint "catalogs_slug_key" UNIQUE using index "catalogs_slug_key";

alter table "public"."catalogs" add constraint "catalogs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."catalogs" validate constraint "catalogs_user_id_fkey";

alter table "public"."product_prices" add constraint "product_prices_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE not valid;

alter table "public"."product_prices" validate constraint "product_prices_product_id_fkey";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "public"."business_social_links" to "anon";

grant insert on table "public"."business_social_links" to "anon";

grant references on table "public"."business_social_links" to "anon";

grant select on table "public"."business_social_links" to "anon";

grant trigger on table "public"."business_social_links" to "anon";

grant truncate on table "public"."business_social_links" to "anon";

grant update on table "public"."business_social_links" to "anon";

grant delete on table "public"."business_social_links" to "authenticated";

grant insert on table "public"."business_social_links" to "authenticated";

grant references on table "public"."business_social_links" to "authenticated";

grant select on table "public"."business_social_links" to "authenticated";

grant trigger on table "public"."business_social_links" to "authenticated";

grant truncate on table "public"."business_social_links" to "authenticated";

grant update on table "public"."business_social_links" to "authenticated";

grant delete on table "public"."business_social_links" to "postgres";

grant insert on table "public"."business_social_links" to "postgres";

grant references on table "public"."business_social_links" to "postgres";

grant select on table "public"."business_social_links" to "postgres";

grant trigger on table "public"."business_social_links" to "postgres";

grant truncate on table "public"."business_social_links" to "postgres";

grant update on table "public"."business_social_links" to "postgres";

grant delete on table "public"."business_social_links" to "service_role";

grant insert on table "public"."business_social_links" to "service_role";

grant references on table "public"."business_social_links" to "service_role";

grant select on table "public"."business_social_links" to "service_role";

grant trigger on table "public"."business_social_links" to "service_role";

grant truncate on table "public"."business_social_links" to "service_role";

grant update on table "public"."business_social_links" to "service_role";

grant delete on table "public"."businesses" to "anon";

grant insert on table "public"."businesses" to "anon";

grant references on table "public"."businesses" to "anon";

grant select on table "public"."businesses" to "anon";

grant trigger on table "public"."businesses" to "anon";

grant truncate on table "public"."businesses" to "anon";

grant update on table "public"."businesses" to "anon";

grant delete on table "public"."businesses" to "authenticated";

grant insert on table "public"."businesses" to "authenticated";

grant references on table "public"."businesses" to "authenticated";

grant select on table "public"."businesses" to "authenticated";

grant trigger on table "public"."businesses" to "authenticated";

grant truncate on table "public"."businesses" to "authenticated";

grant update on table "public"."businesses" to "authenticated";

grant delete on table "public"."businesses" to "postgres";

grant insert on table "public"."businesses" to "postgres";

grant references on table "public"."businesses" to "postgres";

grant select on table "public"."businesses" to "postgres";

grant trigger on table "public"."businesses" to "postgres";

grant truncate on table "public"."businesses" to "postgres";

grant update on table "public"."businesses" to "postgres";

grant delete on table "public"."businesses" to "service_role";

grant insert on table "public"."businesses" to "service_role";

grant references on table "public"."businesses" to "service_role";

grant select on table "public"."businesses" to "service_role";

grant trigger on table "public"."businesses" to "service_role";

grant truncate on table "public"."businesses" to "service_role";

grant update on table "public"."businesses" to "service_role";

grant delete on table "public"."catalog_sections" to "anon";

grant insert on table "public"."catalog_sections" to "anon";

grant references on table "public"."catalog_sections" to "anon";

grant select on table "public"."catalog_sections" to "anon";

grant trigger on table "public"."catalog_sections" to "anon";

grant truncate on table "public"."catalog_sections" to "anon";

grant update on table "public"."catalog_sections" to "anon";

grant delete on table "public"."catalog_sections" to "authenticated";

grant insert on table "public"."catalog_sections" to "authenticated";

grant references on table "public"."catalog_sections" to "authenticated";

grant select on table "public"."catalog_sections" to "authenticated";

grant trigger on table "public"."catalog_sections" to "authenticated";

grant truncate on table "public"."catalog_sections" to "authenticated";

grant update on table "public"."catalog_sections" to "authenticated";

grant delete on table "public"."catalog_sections" to "postgres";

grant insert on table "public"."catalog_sections" to "postgres";

grant references on table "public"."catalog_sections" to "postgres";

grant select on table "public"."catalog_sections" to "postgres";

grant trigger on table "public"."catalog_sections" to "postgres";

grant truncate on table "public"."catalog_sections" to "postgres";

grant update on table "public"."catalog_sections" to "postgres";

grant delete on table "public"."catalog_sections" to "service_role";

grant insert on table "public"."catalog_sections" to "service_role";

grant references on table "public"."catalog_sections" to "service_role";

grant select on table "public"."catalog_sections" to "service_role";

grant trigger on table "public"."catalog_sections" to "service_role";

grant truncate on table "public"."catalog_sections" to "service_role";

grant update on table "public"."catalog_sections" to "service_role";

grant delete on table "public"."catalog_slides" to "anon";

grant insert on table "public"."catalog_slides" to "anon";

grant references on table "public"."catalog_slides" to "anon";

grant select on table "public"."catalog_slides" to "anon";

grant trigger on table "public"."catalog_slides" to "anon";

grant truncate on table "public"."catalog_slides" to "anon";

grant update on table "public"."catalog_slides" to "anon";

grant delete on table "public"."catalog_slides" to "authenticated";

grant insert on table "public"."catalog_slides" to "authenticated";

grant references on table "public"."catalog_slides" to "authenticated";

grant select on table "public"."catalog_slides" to "authenticated";

grant trigger on table "public"."catalog_slides" to "authenticated";

grant truncate on table "public"."catalog_slides" to "authenticated";

grant update on table "public"."catalog_slides" to "authenticated";

grant delete on table "public"."catalog_slides" to "postgres";

grant insert on table "public"."catalog_slides" to "postgres";

grant references on table "public"."catalog_slides" to "postgres";

grant select on table "public"."catalog_slides" to "postgres";

grant trigger on table "public"."catalog_slides" to "postgres";

grant truncate on table "public"."catalog_slides" to "postgres";

grant update on table "public"."catalog_slides" to "postgres";

grant delete on table "public"."catalog_slides" to "service_role";

grant insert on table "public"."catalog_slides" to "service_role";

grant references on table "public"."catalog_slides" to "service_role";

grant select on table "public"."catalog_slides" to "service_role";

grant trigger on table "public"."catalog_slides" to "service_role";

grant truncate on table "public"."catalog_slides" to "service_role";

grant update on table "public"."catalog_slides" to "service_role";

grant delete on table "public"."catalogs" to "anon";

grant insert on table "public"."catalogs" to "anon";

grant references on table "public"."catalogs" to "anon";

grant select on table "public"."catalogs" to "anon";

grant trigger on table "public"."catalogs" to "anon";

grant truncate on table "public"."catalogs" to "anon";

grant update on table "public"."catalogs" to "anon";

grant delete on table "public"."catalogs" to "authenticated";

grant insert on table "public"."catalogs" to "authenticated";

grant references on table "public"."catalogs" to "authenticated";

grant select on table "public"."catalogs" to "authenticated";

grant trigger on table "public"."catalogs" to "authenticated";

grant truncate on table "public"."catalogs" to "authenticated";

grant update on table "public"."catalogs" to "authenticated";

grant delete on table "public"."catalogs" to "postgres";

grant insert on table "public"."catalogs" to "postgres";

grant references on table "public"."catalogs" to "postgres";

grant select on table "public"."catalogs" to "postgres";

grant trigger on table "public"."catalogs" to "postgres";

grant truncate on table "public"."catalogs" to "postgres";

grant update on table "public"."catalogs" to "postgres";

grant delete on table "public"."catalogs" to "service_role";

grant insert on table "public"."catalogs" to "service_role";

grant references on table "public"."catalogs" to "service_role";

grant select on table "public"."catalogs" to "service_role";

grant trigger on table "public"."catalogs" to "service_role";

grant truncate on table "public"."catalogs" to "service_role";

grant update on table "public"."catalogs" to "service_role";

grant delete on table "public"."product_prices" to "anon";

grant insert on table "public"."product_prices" to "anon";

grant references on table "public"."product_prices" to "anon";

grant select on table "public"."product_prices" to "anon";

grant trigger on table "public"."product_prices" to "anon";

grant truncate on table "public"."product_prices" to "anon";

grant update on table "public"."product_prices" to "anon";

grant delete on table "public"."product_prices" to "authenticated";

grant insert on table "public"."product_prices" to "authenticated";

grant references on table "public"."product_prices" to "authenticated";

grant select on table "public"."product_prices" to "authenticated";

grant trigger on table "public"."product_prices" to "authenticated";

grant truncate on table "public"."product_prices" to "authenticated";

grant update on table "public"."product_prices" to "authenticated";

grant delete on table "public"."product_prices" to "postgres";

grant insert on table "public"."product_prices" to "postgres";

grant references on table "public"."product_prices" to "postgres";

grant select on table "public"."product_prices" to "postgres";

grant trigger on table "public"."product_prices" to "postgres";

grant truncate on table "public"."product_prices" to "postgres";

grant update on table "public"."product_prices" to "postgres";

grant delete on table "public"."product_prices" to "service_role";

grant insert on table "public"."product_prices" to "service_role";

grant references on table "public"."product_prices" to "service_role";

grant select on table "public"."product_prices" to "service_role";

grant trigger on table "public"."product_prices" to "service_role";

grant truncate on table "public"."product_prices" to "service_role";

grant update on table "public"."product_prices" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "postgres";

grant insert on table "public"."products" to "postgres";

grant references on table "public"."products" to "postgres";

grant select on table "public"."products" to "postgres";

grant trigger on table "public"."products" to "postgres";

grant truncate on table "public"."products" to "postgres";

grant update on table "public"."products" to "postgres";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Public profiles are viewable by everyone"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert their own profile"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Users can update their own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));


CREATE TRIGGER on_profile_updated BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


