/**
 * Países de América + España (orden: Bolivia primero por defecto, luego resto).
 */
export const COUNTRIES = [
  "Bolivia",
  "Argentina",
  "Belice",
  "Brasil",
  "Canadá",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Ecuador",
  "El Salvador",
  "España",
  "Estados Unidos",
  "Guatemala",
  "Haití",
  "Honduras",
  "Jamaica",
  "México",
  "Nicaragua",
  "Panamá",
  "Paraguay",
  "Perú",
  "República Dominicana",
  "Trinidad y Tobago",
  "Uruguay",
  "Venezuela",
] as const;

export type Country = (typeof COUNTRIES)[number];

/**
 * Ciudades por país (solo países de América + España).
 */
export const CITIES_BY_COUNTRY: Record<string, readonly string[]> = {
  Bolivia: [
    "La Paz",
    "Santa Cruz de la Sierra",
    "Cochabamba",
    "Oruro",
    "Sucre",
    "Tarija",
    "Potosí",
    "Trinidad",
    "Cobija",
    "El Alto",
  ],
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "San Miguel de Tucumán",
    "La Plata",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
  ],
  Belice: ["Belmopán", "Belice", "San Ignacio", "Orange Walk", "Corozal"],
  Brasil: [
    "São Paulo",
    "Río de Janeiro",
    "Brasilia",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
  ],
  Canadá: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec",
  ],
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Temuco",
    "Iquique",
  ],
  Colombia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Bucaramanga",
    "Pereira",
  ],
  "Costa Rica": [
    "San José",
    "Alajuela",
    "Cartago",
    "Heredia",
    "Liberia",
    "Puntarenas",
    "Limón",
  ],
  Cuba: ["La Habana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"],
  Ecuador: [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Machala",
    "Manta",
    "Loja",
    "Ambato",
  ],
  "El Salvador": [
    "San Salvador",
    "Santa Ana",
    "San Miguel",
    "Soyapango",
    "La Libertad",
  ],
  España: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma de Mallorca",
    "Bilbao",
    "Alicante",
  ],
  "Estados Unidos": [
    "Nueva York",
    "Los Ángeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Filadelfia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "Miami",
  ],
  Guatemala: [
    "Ciudad de Guatemala",
    "Quetzaltenango",
    "Escuintla",
    "Mazatenango",
    "Antigua Guatemala",
  ],
  Haití: [
    "Puerto Príncipe",
    "Cap-Haïtien",
    "Gonaïves",
    "Les Cayes",
    "Petionville",
  ],
  Honduras: [
    "Tegucigalpa",
    "San Pedro Sula",
    "Choloma",
    "La Ceiba",
    "El Progreso",
  ],
  Jamaica: ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "Negril"],
  México: [
    "Ciudad de México",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Mérida",
    "Cancún",
  ],
  Nicaragua: ["Managua", "León", "Masaya", "Granada", "Estelí", "Chinandega"],
  Panamá: ["Ciudad de Panamá", "Colón", "David", "La Chorrera", "Santiago"],
  Paraguay: [
    "Asunción",
    "Ciudad del Este",
    "Encarnación",
    "Pedro Juan Caballero",
    "Concepción",
  ],
  Perú: [
    "Lima",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Cusco",
    "Piura",
    "Iquitos",
  ],
  "República Dominicana": [
    "Santo Domingo",
    "Santiago",
    "La Romana",
    "San Pedro de Macorís",
    "Puerto Plata",
  ],
  "Trinidad y Tobago": ["Puerto España", "San Fernando", "Chaguanas", "Arima"],
  Uruguay: [
    "Montevideo",
    "Salto",
    "Paysandú",
    "Las Piedras",
    "Rivera",
    "Maldonado",
  ],
  Venezuela: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
  ],
} as const;

/** Obtiene las ciudades de un país. */
export function getCitiesByCountry(country: string): readonly string[] {
  return CITIES_BY_COUNTRY[country] ?? [];
}
